name: Build and deploy ASP.Net Core app to Azure Web App - Lorby

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Lorby
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: '8.0.x'
  APPLICATION_SOLUTION_FILE: ./src/Lorby.Backend/Lorby.sln

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core application
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.APPLICATION_SOLUTION_FILE }}

      - name: Build
        run: dotnet build ${{ env.APPLICATION_SOLUTION_FILE }} --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ${{ env.APPLICATION_SOLUTION_FILE }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CDB6DA77114441AB175A2CC7AF89D27 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
